version: "{build}"

skip_tags: true

environment:
  matrix:
    # - job_name: VS-2015
    #   appveyor_build_worker_image: Visual Studio 2015
    #   FEATURE: HUGE

    - job_name: VS-2022
      appveyor_build_worker_image: Visual Studio 2022
      FEATURE: HUGE

# disabled
#    - FEATURE: TINY
#    - FEATURE: NORMAL
#    - FEATURE: BIG

matrix:
  fast_finish: true

before_build:
  # Use Visual Studio 2015 compiler tools (default is 2012)
  - setlocal ENABLEDELAYEDEXPANSION
  - call ver
  - reg query "hklm\software\microsoft\windows nt\currentversion" /v ProductName
  - reg query "HKCU\Keyboard Layout\Preload"
  - set "VSWHERE=%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"
  - >
    if exist "%VSWHERE%" (
    for /f "usebackq delims=" %%i
    in (`"%VSWHERE%" -products * -latest -property installationPath`) 
    do (set "VCVARSALL=%%i\VC\Auxiliary\Build\vcvarsall.bat")
    )
  - > 
    if not exist "%VCVARSALL%" (
    set "VCVARSALL=%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
    )
  - call "%VCVARSALL%" x64

build_script:
  - ci/appveyor.bat

test_script:
  - cd src/testdir
    # Testing with MSVC gvim
  - path C:\Python38-x64;%PATH%
  - nmake -f Make_mvc.mak VIMPROG=..\gvim
  - nmake -f Make_mvc.mak clean
    # Testing with MSVC console version
  - nmake -f Make_mvc.mak VIMPROG=..\vim

artifacts:
  - path: src/vim.exe
    name: vim
  - path: src/gvim.exe
    name: gvim

# vim: sw=2 sts=2 et ts=8 sr
